sudo: required
services:
  - docker

before_install:
  - docker build -t davidkur/simpleweb -f Dockerfile.dev .

script:
  - docker run -e CI=true davidkur/simpleweb npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'simpleweb'
  env: 'Simpleweb-env'
  bucket_name: 'arn:aws:s3:::elasticbeanstalk-us-east-2-985424951107'
  bucket_path: 'simpleweb'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
